// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-M8q1Ce6CDj-ZGfNka2kqO2LahbhpE0E',
    appId: '1:75692760111:android:e2b1f8b03df7e129f23ada',
    messagingSenderId: '75692760111',
    projectId: 'babycare-7cb25',
    storageBucket: 'babycare-7cb25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApZamQHCFUIl-0t9YfKTVX-sDmN8S4FhI',
    appId: '1:75692760111:ios:c38cf5af4720df67f23ada',
    messagingSenderId: '75692760111',
    projectId: 'babycare-7cb25',
    storageBucket: 'babycare-7cb25.appspot.com',
    iosBundleId: 'com.example.babycare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApZamQHCFUIl-0t9YfKTVX-sDmN8S4FhI',
    appId: '1:75692760111:ios:c38cf5af4720df67f23ada',
    messagingSenderId: '75692760111',
    projectId: 'babycare-7cb25',
    storageBucket: 'babycare-7cb25.appspot.com',
    iosBundleId: 'com.example.babycare',
  );
}
